version: '3.3'

services:

  db:
    image: mysql:8
    container_name: meet2gether_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretRootPassword
      MYSQL_DATABASE: meet2gether
      MYSQL_USER: meet2getherUser
      MYSQL_PASSWORD: superSecretPassword
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    image: meet2gether
    container_name: meet2gether_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/meet2gether?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: meet2getherUser
      SPRING_DATASOURCE_PASSWORD: superSecretPassword
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: